apiVersion: v1
kind: ConfigMap
metadata:
  name: common-shell-app-config

data:
  nginxPort: "{{.Values.pod.containerPort}}"
  dockerHost: "{{.Values.dockerHost}}"
  hostName: localhost
  remoteAName: {{.Values.remoteA.name}}
  remoteBName: {{.Values.remoteB.name}}

