
pod:
 containerName: "container"
 imageName: ""
 containerPort: 80


services:
  name: "service"
  type: NodePort  #due to external IP pending issue, changed from LoadBalancer to NodePort
  app:
   dev: 8086
   uat: 8087
   prod: 8088
  node:
   dev: 30004
   uat: 30014
   prod: 30024

remoteA:
 dev: '30006'
 uat: '30016'
 prod: '30026'

remoteB:
 dev: '30008'
 uat: '30018'
 prod: '30028'
   

environment: ""

config:
  name: shell-app-config
  volume: shell-app-config-vol
  mountPath: config
